{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "estafette-vulnerability-scanner.fullname" . }}
  labels:
{{ include "estafette-vulnerability-scanner.labels" . | indent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  - jobs
  - cronjobs
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - list
{{- end -}}
